//! Beacon — the cryptographic ticket that grants Constellation membership.
//!
//! A Beacon contains everything a node needs to join the Constellation:
//! a [`DocTicket`] from iroh-docs, which carries the namespace capability
//! (read/write keys) and the bootstrap peer's [`EndpointAddr`].
//!
//! **The Beacon IS the membership credential.** Anyone holding the Beacon can
//! import the Doc, sync state, and connect to Satellites.
//!
//! Wire format: `orbit-v1-<base64url-encoded-postcard(DocTicket)>`

use std::fmt;

use anyhow::{Context, Result, ensure};
use data_encoding::BASE64URL_NOPAD;
use iroh_docs::DocTicket;

/// Version prefix for our Beacon encoding.
const BEACON_PREFIX: &str = "orbit-v1-";

/// A Beacon is a self-contained cryptographic ticket for Constellation membership.
///
/// It wraps an iroh-docs [`DocTicket`], which carries:
/// - The **namespace capability** (read/write keys) — the membership credential.
/// - The Station's **EndpointAddr** — the bootstrap peer for initial sync.
///
/// The Beacon is generated by the Station during `station init` and distributed
/// to Satellites and Mission Control nodes.
#[derive(Debug, Clone)]
pub struct Beacon {
    doc_ticket: DocTicket,
}

impl Beacon {
    /// Create a new Beacon from a DocTicket.
    pub fn new(doc_ticket: DocTicket) -> Self {
        Self { doc_ticket }
    }

    /// The underlying DocTicket — used to import the Doc and start syncing.
    pub fn doc_ticket(&self) -> &DocTicket {
        &self.doc_ticket
    }

    /// Consume the Beacon and return the inner DocTicket.
    pub fn into_doc_ticket(self) -> DocTicket {
        self.doc_ticket
    }

    /// Serialize the Beacon to a shareable string.
    ///
    /// Format: `orbit-v1-<base64url(postcard(DocTicket))>`
    pub fn serialize(&self) -> String {
        let payload = postcard::to_stdvec(&self.doc_ticket)
            .expect("postcard serialization of DocTicket is infallible");
        format!("{BEACON_PREFIX}{}", BASE64URL_NOPAD.encode(&payload))
    }

    /// Deserialize a Beacon from its string representation.
    pub fn deserialize(s: &str) -> Result<Self> {
        ensure!(
            s.starts_with(BEACON_PREFIX),
            "Beacon must start with '{BEACON_PREFIX}'"
        );
        let encoded = &s[BEACON_PREFIX.len()..];
        let payload = BASE64URL_NOPAD
            .decode(encoded.as_bytes())
            .context("failed to decode Beacon base64url payload")?;
        let doc_ticket: DocTicket = postcard::from_bytes(&payload)
            .context("failed to decode Beacon postcard payload")?;
        Ok(Self { doc_ticket })
    }
}

impl fmt::Display for Beacon {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.serialize())
    }
}

impl std::str::FromStr for Beacon {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::deserialize(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use iroh::PublicKey;
    use iroh_docs::{Capability, NamespaceId};

    fn make_test_doc_ticket() -> DocTicket {
        // Create a minimal valid DocTicket with a random namespace and a node
        let pk = PublicKey::from_bytes(&[0u8; 32]).unwrap();
        let addr = iroh::EndpointAddr::new(pk);
        let namespace_id = NamespaceId::from([42u8; 32]);
        DocTicket::new(Capability::Read(namespace_id), vec![addr])
    }

    #[test]
    fn beacon_roundtrip() {
        let ticket = make_test_doc_ticket();
        let beacon = Beacon::new(ticket);
        let encoded = beacon.serialize();
        let decoded = Beacon::deserialize(&encoded).unwrap();
        assert_eq!(decoded.doc_ticket().capability.id(), beacon.doc_ticket().capability.id());
    }

    #[test]
    fn beacon_roundtrip_display_from_str() {
        let ticket = make_test_doc_ticket();
        let beacon = Beacon::new(ticket);
        let encoded = beacon.to_string();
        let decoded: Beacon = encoded.parse().unwrap();
        assert_eq!(decoded.doc_ticket().capability.id(), beacon.doc_ticket().capability.id());
    }

    #[test]
    fn beacon_has_prefix() {
        let ticket = make_test_doc_ticket();
        let beacon = Beacon::new(ticket);
        let encoded = beacon.serialize();
        assert!(encoded.starts_with("orbit-v1-"));
    }

    #[test]
    fn beacon_rejects_missing_prefix() {
        let result = Beacon::deserialize("not-a-beacon");
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("must start with"));
    }

    #[test]
    fn beacon_rejects_invalid_base64() {
        let result = Beacon::deserialize("orbit-v1-!!!invalid!!!");
        assert!(result.is_err());
    }

    #[test]
    fn beacon_rejects_invalid_postcard() {
        // Valid base64url but garbage postcard data
        let garbage = BASE64URL_NOPAD.encode(&[0xDE, 0xAD, 0xBE, 0xEF]);
        let encoded = format!("orbit-v1-{garbage}");
        let result = Beacon::deserialize(&encoded);
        assert!(result.is_err());
    }

    #[test]
    fn beacon_doc_ticket_accessor() {
        let ticket = make_test_doc_ticket();
        let beacon = Beacon::new(ticket.clone());
        assert_eq!(beacon.doc_ticket().capability.id(), ticket.capability.id());
    }

    #[test]
    fn beacon_with_write_capability() {
        // Test with a Write capability (NamespaceSecret)
        let secret = iroh_docs::NamespaceSecret::from_bytes(&[7u8; 32]);
        let pk = PublicKey::from_bytes(&[0u8; 32]).unwrap();
        let addr = iroh::EndpointAddr::new(pk);
        let ticket = DocTicket::new(Capability::Write(secret), vec![addr]);
        let beacon = Beacon::new(ticket);
        let encoded = beacon.to_string();
        let decoded: Beacon = encoded.parse().unwrap();
        assert_eq!(decoded.doc_ticket().capability.id(), beacon.doc_ticket().capability.id());
    }
}
